namespace LittleToySourceGenerator.Tests;

using Microsoft.CodeAnalysis;
using Microsoft.VisualStudio.TestTools.UnitTesting;

[TestClass]
public class GenerateEventViewInterfaceTests : CodeGenerationTestBase
{
    [TestMethod]
    public void DirtyEventViewInterfaces()
    {
        string source = @"
using Plugins.basegame.Events;

[Plugins.basegame.Events.ComponentDirtyEvent]
public partial struct Position3Data : Unity.Entities.IComponentData
{
    public Unity.Mathematics.float3 Value;
}

[Plugins.basegame.Events.ComponentDirtyEvent]
public partial struct RotationQuaternionData : Unity.Entities.IComponentData
{
    public Unity.Mathematics.quaternion Value;
}

[OnDirtyEventView(typeof(Position3Data), typeof(RotationQuaternionData))]
public partial class TransformView : LinkedView
{
    public virtual void OnPosition3Changed(float3 value)
    {
        transform.position = value;
    }
    
    public virtual void OnRotationQuaternionChanged(quaternion value)
    {
        transform.rotation = value;
    }
}
";
        var generator = new Generator();
        generator.DisableAllGeneration();
        generator.GenerateEventViewInterfaceGeneration = true;
        string output = this.GetGeneratedOutput(source, generator, NullableContextOptions.Disable);

        Assert.IsNotNull(output);

        var expectedOutput = @"// <auto-generated>
// Code generated by LittleToy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
#pragma warning disable 1591


public partial class TransformView : IPosition3Listener, IRotationQuaternionListener
{
}
";
        Assert.AreEqual(expectedOutput, output);
    }

    [TestMethod]
    public void OnAddedEventViewInterfaces()
    {
        string source = @"
using Plugins.basegame.Events;

[Plugins.basegame.Events.ComponentDirtyEvent]
public partial struct Position3Data : Unity.Entities.IComponentData
{
    public Unity.Mathematics.float3 Value;
}

[Plugins.basegame.Events.ComponentDirtyEvent]
public partial struct RotationQuaternionData : Unity.Entities.IComponentData
{
    public Unity.Mathematics.quaternion Value;
}

[OnAddedEventView(typeof(Position3Data), typeof(RotationQuaternionData))]
public partial class TransformView : LinkedView
{
    public virtual void OnPosition3Added()
    {
    }
    
    public virtual void OnRotationQuaternionAdded()
    {
    }
}
";
        var generator = new Generator();
        generator.DisableAllGeneration();
        generator.GenerateEventViewInterfaceGeneration = true;
        string output = this.GetGeneratedOutput(source, generator, NullableContextOptions.Disable);

        Assert.IsNotNull(output);

        var expectedOutput = @"// <auto-generated>
// Code generated by LittleToy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
#pragma warning disable 1591


public partial class TransformView : IPosition3AddedListener, IRotationQuaternionAddedListener
{
}
";
        Assert.AreEqual(expectedOutput, output);
    }

    [TestMethod]
    public void OnRemovedEventViewInterfaces()
    {
        string source = @"
using Plugins.basegame.Events;

[Plugins.basegame.Events.ComponentDirtyEvent]
public partial struct Position3Data : Unity.Entities.IComponentData
{
    public Unity.Mathematics.float3 Value;
}

[Plugins.basegame.Events.ComponentDirtyEvent]
public partial struct RotationQuaternionData : Unity.Entities.IComponentData
{
    public Unity.Mathematics.quaternion Value;
}

[OnRemovedEventView(typeof(Position3Data), typeof(RotationQuaternionData))]
public partial class TransformView : LinkedView
{
    public virtual void OnPosition3Removed()
    {
    }
    
    public virtual void OnRotationQuaternionRemoved()
    {
    }
}
";
        var generator = new Generator();
        generator.DisableAllGeneration();
        generator.GenerateEventViewInterfaceGeneration = true;
        string output = this.GetGeneratedOutput(source, generator, NullableContextOptions.Disable);

        Assert.IsNotNull(output);

        var expectedOutput = @"// <auto-generated>
// Code generated by LittleToy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
#pragma warning disable 1591


public partial class TransformView : IPosition3RemovedListener, IRotationQuaternionRemovedListener
{
}
";
        Assert.AreEqual(expectedOutput, output);
    }

    [TestMethod]
    public void DirtyEventViewInterfacesWithDifferentNamespaces()
    {
        string source = @"
using Plugins.basegame.Events;

namespace Test1.Internal
{
    [Plugins.basegame.Events.ComponentDirtyEvent]
    public partial struct Position3Data : Unity.Entities.IComponentData
    {
        public Unity.Mathematics.float3 Value;
    }
}

namespace Test2.ChildNamespace
{
    [Plugins.basegame.Events.ComponentDirtyEvent]
    public partial struct RotationQuaternionData : Unity.Entities.IComponentData
    {
        public Unity.Mathematics.quaternion Value;
    }
}

namespace My.Views
{
    using Test1.Internal;
    using Test2.ChildNamespace;

    [OnDirtyEventView(typeof(Position3Data), typeof(RotationQuaternionData))]
    public partial class TransformView : LinkedView
    {
        public virtual void OnPosition3Changed(float3 value)
        {
            transform.position = value;
        }
    
        public virtual void OnRotationQuaternionChanged(quaternion value)
        {
            transform.rotation = value;
        }
    }
}
";
        var generator = new Generator();
        generator.DisableAllGeneration();
        generator.GenerateEventViewInterfaceGeneration = true;
        string output = this.GetGeneratedOutput(source, generator, NullableContextOptions.Disable);

        Assert.IsNotNull(output);

        var expectedOutput = @"// <auto-generated>
// Code generated by LittleToy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
#pragma warning disable 1591


namespace My.Views
{

    public partial class TransformView : Test1.Internal.IPosition3Listener, Test2.ChildNamespace.IRotationQuaternionListener
    {
    }
}
";
        Assert.AreEqual(expectedOutput, output);
    }

    [TestMethod]
    public void OnAddedEventViewInterfacesWithDifferentNamespaces()
    {
        string source = @"
using Plugins.basegame.Events;

namespace Test1.Internal
{
    [Plugins.basegame.Events.ComponentDirtyEvent]
    public partial struct Position3Data : Unity.Entities.IComponentData
    {
        public Unity.Mathematics.float3 Value;
    }
}

namespace Test2.ChildNamespace
{
    [Plugins.basegame.Events.ComponentDirtyEvent]
    public partial struct RotationQuaternionData : Unity.Entities.IComponentData
    {
        public Unity.Mathematics.quaternion Value;
    }
}

namespace My.Views
{
    using Test1.Internal;
    using Test2.ChildNamespace;

    [OnAddedEventView(typeof(Position3Data), typeof(RotationQuaternionData))]
    public partial class TransformView : LinkedView
    {
        public virtual void OnPosition3Added()
        {
        }
    
        public virtual void OnRotationQuaternionAdded()
        {
        }
    }
}
";
        var generator = new Generator();
        generator.DisableAllGeneration();
        generator.GenerateEventViewInterfaceGeneration = true;
        string output = this.GetGeneratedOutput(source, generator, NullableContextOptions.Disable);

        Assert.IsNotNull(output);

        var expectedOutput = @"// <auto-generated>
// Code generated by LittleToy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
#pragma warning disable 1591


namespace My.Views
{

    public partial class TransformView : Test1.Internal.IPosition3AddedListener, Test2.ChildNamespace.IRotationQuaternionAddedListener
    {
    }
}
";
        Assert.AreEqual(expectedOutput, output);
    }

    [TestMethod]
    public void OnRemovedEventViewInterfacesWithDifferentNamespaces()
    {
        string source = @"
using Plugins.basegame.Events;

namespace Test1.Internal
{
    [Plugins.basegame.Events.ComponentDirtyEvent]
    public partial struct Position3Data : Unity.Entities.IComponentData
    {
        public Unity.Mathematics.float3 Value;
    }
}

namespace Test2.ChildNamespace
{
    [Plugins.basegame.Events.ComponentDirtyEvent]
    public partial struct RotationQuaternionData : Unity.Entities.IComponentData
    {
        public Unity.Mathematics.quaternion Value;
    }
}

namespace My.Views
{
    using Test1.Internal;
    using Test2.ChildNamespace;

    [OnRemovedEventView(typeof(Position3Data), typeof(RotationQuaternionData))]
    public partial class TransformView : LinkedView
    {
        public virtual void OnPosition3Removed()
        {
        }
    
        public virtual void OnRotationQuaternionRemoved()
        {
        }
    }
}
";
        var generator = new Generator();
        generator.DisableAllGeneration();
        generator.GenerateEventViewInterfaceGeneration = true;
        string output = this.GetGeneratedOutput(source, generator, NullableContextOptions.Disable);

        Assert.IsNotNull(output);

        var expectedOutput = @"// <auto-generated>
// Code generated by LittleToy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
#pragma warning disable 1591


namespace My.Views
{

    public partial class TransformView : Test1.Internal.IPosition3RemovedListener, Test2.ChildNamespace.IRotationQuaternionRemovedListener
    {
    }
}
";
        Assert.AreEqual(expectedOutput, output);
    }
}
