namespace LittleToySourceGenerator.Tests;

using Microsoft.CodeAnalysis;
using Microsoft.VisualStudio.TestTools.UnitTesting;

[TestClass]
public class GenerateSelectiveComponentDataAuthoringTests : CodeGenerationTestBase
{
    [TestMethod]
    public void SelectiveComponentDataAuthoringGeneration()
    {
        string source = @"
using Plugins.basegame.Events;
using Unity.Entities;

[GenerateSelectiveComponentDataAuthoring]
public partial struct JoinWorldMessage : IComponentData
{
    public long PlayerId;
}
";
        var generator = new Generator();
        generator.DisableAllGeneration();
        generator.EnableSelectiveComponentDataAuthoringGeneration = true;
        string output = this.GetGeneratedOutput(source, generator, NullableContextOptions.Disable);

        Assert.IsNotNull(output);

        var expectedOutput = @"// <auto-generated>
// Code generated by LittleToy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
#pragma warning disable 1591
using Unity.Entities;

public partial class JoinWorldMessageAuthoring : SelectiveComponentDataAuthoring
{
    protected override void SelectiveConvert(Entity entity, EntityManager dstManager, GameObjectConversionSystem conversionSystem)
    {
        dstManager.AddComponent<JoinWorldMessage>(entity);
    }
}
";
        Assert.AreEqual(expectedOutput, output);
    }

    [TestMethod]
    public void SelectiveComponentDataAuthoringGenerationInsideNamespace()
    {
        string source = @"
using Plugins.basegame.Events;
using Unity.Entities;

namespace Test.InnerNamespace
{
    [GenerateSelectiveComponentDataAuthoringAttribute]
    public partial struct JoinWorldMessage : IComponentData
    {
        public long PlayerId;
    }
}
";
        var generator = new Generator();
        generator.DisableAllGeneration();
        generator.EnableSelectiveComponentDataAuthoringGeneration = true;
        string output = this.GetGeneratedOutput(source, generator, NullableContextOptions.Disable);

        Assert.IsNotNull(output);

        var expectedOutput = @"// <auto-generated>
// Code generated by LittleToy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
#pragma warning disable 1591
using Unity.Entities;

namespace Test.InnerNamespace
{

    public partial class JoinWorldMessageAuthoring : SelectiveComponentDataAuthoring
    {
        protected override void SelectiveConvert(Entity entity, EntityManager dstManager, GameObjectConversionSystem conversionSystem)
        {
            dstManager.AddComponent<Test.InnerNamespace.JoinWorldMessage>(entity);
        }
    }
}
";
        Assert.AreEqual(expectedOutput, output);
    }
}
